#!/usr/bin/env bash
#A file on how to configure a nginx server
#listen to port 80
#use sudo to restart server
apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
