#!/usr/bin/env bash
#A file on how to configure a nginx server

sudo apt-get -y update

sudo apt-get install -y nginx
ufw allow "NGINX HTTP"

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
