#!/usr/bin/env bash
#A file on how to configure a nginx server

apt-get -y update
apt-get -y install nginx
ufw allow "NGINX HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx resta
