#!/usr/bin/env bash
#A file on how to configure a nginx server

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
