#!/usr/bin/env bash
#A file on how to configure a nginx server

sudo apt-get -y update

sudo apt-get install -y nginx
ufw allow "NGINX HTTP"

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name_/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
/etc/nginx/sites-enabled/default

sudo service nginx restart
