#!/usr/bin/env bash
#updating packages before performing installations

sudo apt-get -y update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo echo 'add_header X-Served-BY $hostname;' | sudo tee /etc/nginx/conf.d/custom_header.conf
service nginx start
