#!/usr/bin/env bash
#updating packages before performing installations

sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    add_header X-Served-By $hostname;
    location / {
        # Your additional configurations go here
        # ...
        try_files $uri $uri/ =404;
    }
}
EOF'

# Reload Nginx to apply changes
sudo systemctl reload nginx

# Output a message indicating successful configuration
echo "Nginx has been configured with a custom HTTP header. X-Served-By: $hostname"
