#!/usr/bin/env bash
#Script that displays time
hour=0
minutes=1
while [ $hour -ne 13 ]
do
	echo "Hour: $hour"
	((hour++))
	while [ $minutes -ne 60 ]
	do
		echo $minutes
		((minutes++))
	done
	((minutes = 1))
done
