#!/usr/bin/env bash
#Script that displays time
hours=0
minutes=1
while [ $hours -ne 13 ]
do
	echo "Hours: $hours"
	((hours++))
	while [ $minutes -ne 60 ]
	do
		echo $minutes
		((minutes++))
	done
	((minutes = 1))
done
