#!/usr/bin/env bash
#installing UFW, uncomplicated firewall and configuring it.

sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outcoming
sudo ufw allow 22/tcp
sudo ufw allow 443/top
sudo ufw allow 80/tcp
sudo ufw enable
